title: Pandemic Data Room
logo: /assets/img/sunrise1.jpg
description: A Resource Provided by The Center for Global Data Visualization
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

