title: Pandemic Data Room
logo: /assets/img/sunrise.jpg
description: A Resource Provided by The Center for Global Data Visualization
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
